### ISSUE TITLE
Isar code stripped in android appbundle

### ISSUE THREAD

**Issue by mrclauss** [isar/isar#1044]
I just built a new version of my app, running into the following issue. After some investigation the same issue now also happens when rebuilding the released versions:

2023-01-15 23:04:56.759 7202-7202/? E/t.contactulater: No implementation found for void dev.isar.isar_flutter_libs.IsarInitializer.c(java.lang.String) (tried Java_dev_isar_isar_1flutter_1libs_IsarInitializer_c and Java_dev_isar_isar_1flutter_1libs_IsarInitializer_c__Ljava_lang_String_2)
2023-01-15 23:04:56.760 7202-7202/? D/AndroidRuntime: Shutting down VM
2023-01-15 23:04:56.760 7202-7202/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: es.com.skynet.contactulater, PID: 7202
    java.lang.RuntimeException: Unable to get provider androidx.startup.InitializationProvider: androidx.startup.c: java.lang.UnsatisfiedLinkError: No implementation found for void dev.isar.isar_flutter_libs.IsarInitializer.c(java.lang.String) (tried Java_dev_isar_isar_1flutter_1libs_IsarInitializer_c and Java_dev_isar_isar_1flutter_1libs_IsarInitializer_c__Ljava_lang_String_2)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7493)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6999)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6770)
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:201)
        at android.os.Looper.loop(Looper.java:288)
        at android.app.ActivityThread.main(ActivityThread.java:7898)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
     Caused by: androidx.startup.c: java.lang.UnsatisfiedLinkError: No implementation found for void dev.isar.isar_flutter_libs.IsarInitializer.c(java.lang.String) (tried Java_dev_isar_isar_1flutter_1libs_IsarInitializer_c and Java_dev_isar_isar_1flutter_1libs_IsarInitializer_c__Ljava_lang_String_2)
        at androidx.startup.a.b(:2)
        at androidx.startup.a.a(Unknown Source:83)
        at androidx.startup.InitializationProvider.onCreate(:3)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2451)
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2421)
        at android.app.ActivityThread.installProvider(ActivityThread.java:7488)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6999) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6770) 
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7898) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 
     Caused by: java.lang.UnsatisfiedLinkError: No implementation found for void dev.isar.isar_flutter_libs.IsarInitializer.c(java.lang.String) (tried Java_dev_isar_isar_1flutter_1libs_IsarInitializer_c and Java_dev_isar_isar_1flutter_1libs_IsarInitializer_c__Ljava_lang_String_2)
        at dev.isar.isar_flutter_libs.IsarInitializer.c(Native Method)
        at dev.isar.isar_flutter_libs.IsarInitializer.b(:1)
        at androidx.startup.a.b(:2) 
        at androidx.startup.a.a(Unknown Source:83) 
        at androidx.startup.InitializationProvider.onCreate(:3) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2451) 
        at android.content.ContentProvider.attachInfo(ContentProvider.java:2421) 
        at android.app.ActivityThread.installProvider(ActivityThread.java:7488) 
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6999) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6770) 
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2134) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:201) 
        at android.os.Looper.loop(Looper.java:288) 
        at android.app.ActivityThread.main(ActivityThread.java:7898) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) 

Unzipping the appbundle shows that the classes.dex files are suddenly significantly smaller, seems like some code is stripped during the bundle process...
libisar.so itself seems to be identical to previous builds....
Any ideas what's suddenly going wrong here?

**Comment by mrclauss** [comment]
Seems related to the build machine, does not happen on another computer with the same build environment

**Comment by mrclauss** [comment]
So I digged deeper into this. Issue is that (for whatever black magic reason) on one build machine the default android proguard setting switched to "obfuscate". Disabling obfuscation solves this for me for the moment.
@simc Where could I document this? Is there some knowledge base for issue like this already?

**Comment by mrclauss** [comment]
So the solution/workaround is as follows: If not already present integrate a proguard rules file into your build.
Put a file named "proguard-rules.pro" into folder android/app/ (next to build.gradle)
Put the following line into that file to disable obfuscation:
-dontobfuscate

Not a full solution but at least a workaround.

**Comment by chenjie4255** [comment]
> So the solution/workaround is as follows: If not already present integrate a proguard rules file into your build. Put a file named "proguard-rules.pro" into folder android/app/ (next to build.gradle) Put the following line into that file to disable obfuscation: -dontobfuscate
> 
> Not a full solution but at least a workaround.

Your solution works, thanks so much.

**Comment by CarloDotLog** [comment]
> So the solution/workaround is as follows: If not already present integrate a proguard rules file into your build. Put a file named "proguard-rules.pro" into folder android/app/ (next to build.gradle) Put the following line into that file to disable obfuscation: -dontobfuscate
> 
> Not a full solution but at least a workaround.

It works for me. Thanks for sharing.
