### ISSUE TITLE
Enum index query fails 

### ISSUE THREAD

**Issue by wwwdata** [isar/isar#1164]
### Steps to Reproduce

Hi, I am using a class with a List of enums. So far my code runs fine on iOS and Android. But while writing tests, I noticed it is not working on macOS, where I run my tests on. I developed a small example that reproduces the issue. The query fails with some internal type casting error when using the `@Index` field of a field that is a `List<EnumType>`

### Error message
```
Unhandled exception:
type 'List<dynamic>' is not a subtype of type 'List<String?>' in type cast
#0      _addKeyValue (package:isar/src/native/index_key.dart:173:15)
#1      buildIndexKey (package:isar/src/native/index_key.dart:28:5)
#2      _buildLowerIndexBound (package:isar/src/native/query_build.dart:139:22)
#3      _addIndexWhereClause (package:isar/src/native/query_build.dart:199:20)
#4      buildNativeQuery (package:isar/src/native/query_build.dart:35:7)
#5      IsarCollectionImpl.buildQuery (package:isar/src/native/isar_collection_impl.dart:598:12)
#6      QueryBuilderInternal.build (package:isar/src/query_builder.dart:281:24)
#7      QueryExecute.build (package:isar/src/query_builder_extensions.dart:194:30)
#8      QueryExecute.findAll (package:isar/src/query_builder_extensions.dart:203:32)
#9      main (package:isar_tester/main.dart:20:69)
```

### Code sample

```dart
import 'dart:io';

import 'package:isar/isar.dart';

part 'main.g.dart';

void main(List<String> args) async {
  await Isar.initializeIsarCore(download: true);
  final isar = await Isar.open([TestStructSchema]);

  await isar.writeTxn(() async {
    final testStruct = TestStruct(
      title: 'title',
      attributes: [Attributes.boring],
    );
    await isar.testStructs.put(testStruct);
  });

  final fromDb = await isar.testStructs
      .where()
      .attributesEqualTo([Attributes.cool]).findAll();

  print('result $fromDb');
  exit(0);
}

@collection
class TestStruct {
  TestStruct({
    required this.title,
    required this.attributes,
  });

  Id id = Isar.autoIncrement;

  @Index(type: IndexType.value)
  String title;

  @Index()
  @Enumerated(EnumType.name)
  List<Attributes> attributes;
}

enum Attributes { cool, fast, boring }
```

### Details

 - Platform: macOS
 - Isar version: 3.0.5

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by wwwdata** [comment]
Correction: I tested wrong, it also fails on iOS and Android... Going to work around this now by making some getters that return me bools for flags I am interested in combination :)

**Comment by simc** [comment]
This issue is obsolete for v4
