### ISSUE TITLE
 Exception: RangeError (byteOffset): Invalid value: Not in inclusive range 0..37: 43

### ISSUE THREAD

**Issue by yichaosun** [isar/isar#1304]
### Code sample

```dart
  Future<List<Todo>> getTodoItemAsync() async {
    Query<Todo> createdTodosQuery =
        isar.todos.filter().statusEqualTo(TodoStatus.created).build();
    return createdTodosQuery.findAll();
  }
```
then throw the exception
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (byteOffset): Invalid value: Not in inclusive range 0..37: 43
#0      _ByteDataView.getInt64 (dart:typed_data-patch/typed_data_patch.dart:5004:7)
#1      IsarReaderImpl.readLongList (package:isar/src/native/isar_reader_impl.dart:430:27)
#2      _scheduleDeserialize (package:flutter_demo/domain/todo/schedule.g.dart:97:33)
#3      IsarReaderImpl.readObjectOrNull (package:isar/src/native/isar_reader_impl.dart:268:23)
#4      _todoDeserialize (package:flutter_demo/domain/todo/todo.g.dart:177:28)
#5      IsarCollectionImpl.deserializeObject (package:isar/src/native/isar_collection_impl.dart:42:38)
#6      IsarCollectionImpl.deserializeObjects (package:isar/src/native/isar_collection_impl.dart:66:22)
#7      QueryImpl.findInternal.<anonymous closure> (package:isar/src/native/query_impl.dart:51:27)
<asynchronous suspension>
#8      IsarCommon._beginTxn (package:isar/src/common/isar_common.dart:54:18)
```

### Details

 - Platform: MacOS 12.3.1 
 - Flutter version: 3.10.4
 - Isar version: 3.0.5

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by yichaosun** [comment]
it seems fixed in 3.1.0, when I upgrade the Isar version , wouldn't`t happen again
