### ISSUE TITLE
Failed to lookup symbol 'isar_version': dlsym(RTLD_DEFAULT, isar_version): symbol not found

### ISSUE THREAD

**Issue by DuJerry** [isar/isar#1330]
### Steps to Reproduce

It works normally in debug mode, but the following error occurs in release mode。

`
2023-07-14 17:17:20.215026+0800 Runner[1369:162548] Metal GPU Frame Capture Enabled

2023-07-14 17:17:20.215142+0800 Runner[1369:162548] Metal API Validation Enabled

2023-07-14 17:17:20.305354+0800 Runner[1369:162548] [VERBOSE-2:FlutterDarwinContextMetalImpeller.mm(35)] Using the Impeller rendering backend.

2023-07-14 17:17:20.321229+0800 Runner[1369:162548] Initialized TensorFlow Lite runtime.
INFO: Initialized TensorFlow Lite runtime.

2023-07-14 17:17:20.326432+0800 Runner[1369:162548] Created TensorFlow Lite XNNPACK delegate for CPU.
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.

2023-07-14 17:17:20.421157+0800 Runner[1369:162819] flutter: IsarError: Could not initialize IsarCore library for processor architecture "ios_arm64". If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies.

2023-07-14 17:17:20.421195+0800 Runner[1369:162819] flutter: Invalid argument(s): Failed to lookup symbol 'isar_version': dlsym(RTLD_DEFAULT, isar_version): symbol not found

2023-07-14 17:17:20.421370+0800 Runner[1369:162819] flutter: #0      initializeCoreBinary (package:isar/src/native/isar_core.dart:78)

2023-07-14 17:17:20.421388+0800 Runner[1369:162819] flutter: #1      openIsar (package:isar/src/native/open.dart:81)

2023-07-14 17:17:20.421402+0800 Runner[1369:162819] flutter: #2      Isar.open (package:isar/src/isar.dart:107)`

### Code sample

```dart
Provide a few simple lines of code to show your problem.
```

### Details

 - Platform: iPhone 13 Pro
 - Flutter version: [3.10.5]
 - Isar version: [3.1.0+1]

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by DuJerry** [comment]
I solved this problem by setting Runner->Build setting -> Dead code Strpping for No
