### ISSUE TITLE
Enum Error:  Converting object to an encodable object failed

### ISSUE THREAD

**Issue by juliaen-dr** [isar/isar#1373]
### Steps to Reproduce

I've created a Collection Model with a Field from an enum type. When I create an object of that model an try to PUT it into the database, I'll get a `Converting object to an encodable object failed` error.

### Code sample

```dart
enum ExampleEnum {
  value1('Value1'),
  value2('Value2'),
  value3('Value3'),
  value4('Value4');

  const ExampleEnum(this.value);

  @enumValue
  final String value;
}

Collection(inheritance: false)
class Example extends Equatable {
  @Id()
  final String id;
  final ExampleEnum exampleEnum;


  Example(
    this.id,
    this.exampleEnum,
  );

  @override
  List<dynamic> get props => [
        id,
        exampleEnum,
   ];
}
```

If I try to put something in the database now, like this:

```dart
   await _isarDB.writeAsync((_isarDB) {
        _isarDB.examples.put(
               ExampleClass(
                     '123',
                     ExampleEnum.value1,
                ),
        ),},
    );
```
I'll get this error:

`
                       Converting object to an encodable object failed: Instance of 'ExampleEnum'
                       #0      _JsonStringifier.writeObject (dart:convert/json.dart:793:7)
                       #1      _JsonStringifier.writeList (dart:convert/json.dart:844:9)
                       #2      _JsonStringifier.writeJsonValue (dart:convert/json.dart:823:7)
                       #3      _JsonStringifier.writeObject (dart:convert/json.dart:784:9)
                       #4      _JsonStringStringifier.printOn (dart:convert/json.dart:982:17)
                       #5      _JsonStringStringifier.stringify (dart:convert/json.dart:967:5)
                       #6      JsonEncoder.convert (dart:convert/json.dart:345:30)
                       #7      JsonCodec.encode (dart:convert/json.dart:231:45)
                       #8      jsonEncode (dart:convert/json.dart:114:10)
                       #9      serializeDeployment (package:app/models/example.g.dart:83:50)
                       #10     _IsarCollectionImpl.putAll.<anonymous closure> (package:isar/src/impl/isar_collection_impl.dart:100:41)
                       #11     _IsarImpl.getWriteTxn (package:isar/src/impl/isar_impl.dart:201:47)
                       #12     _IsarCollectionImpl.putAll (package:isar/src/impl/isar_collection_impl.dart:84:17)
                       #13     IsarCollection.put (package:isar/src/isar_collection.dart:29:27)
`
### Details

 - Platform: Android
 - Flutter version: 3.0.0
 - Isar version: 4.0.0-dev.5

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by simc** [comment]
Isar tries to serialize your `props` property as JSON and fails because the enum does not support that. Annotate props with `@ignore` to fix the issue
