### ISSUE TITLE
openSync fails on API 30; IsarError: Cannot open Environment: MdbxError (75): Value too large for defined data type

### ISSUE THREAD

**Issue by tomekit** [isar/isar#1492]
### Steps to Reproduce

openSync fails during app start, but only on Android API 30 emulator. It works fine on API 29 or API33.
```
I/flutter ( 3349): Error:  IsarError: Cannot open Environment: MdbxError (75): Value too large for defined data type
I/flutter ( 3349): Stacktrace:  #0      nCall (package:isar/src/native/isar_core.dart:174:5)
I/flutter ( 3349): #1      openIsarSync.<anonymous closure> (package:isar/src/native/open.dart:141:5)
I/flutter ( 3349): #2      using (package:ffi/src/arena.dart:124:31)
I/flutter ( 3349): #3      openIsarSync (package:isar/src/native/open.dart:129:10)
I/flutter ( 3349): #4      Isar.openSync (package:isar/src/isar.dart:137:12)
```

### Code sample

```dart
final scopeKey = "instance";
final dir = await getApplicationSupportDirectory();
    final scopedDir = "${dir.path}${p.separator}$scopeKey";
    await Directory(scopedDir).create(recursive: true);

    Isar db = Isar.openSync(
      [
        LoggerSchema,
      ],
      directory: scopedDir,
      name: scopeKey,
    );
```

### Details

 - Platform: Pixel 6 API 30
 - Flutter version: 3.13.9
 - Isar version: 3.1.0+1 

---

 - [x ] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [partially] I am able to provide a reproducible example

**Comment by myyvee** [comment]
I agree with tomekit - I have observed the same problem:

E/flutter ( 7444): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: IsarError: Cannot open Environment: MdbxError (75): Value too large for defined data type

The problem only occurs in the emulator on API 30, "smaller" and "larger" APIs are not affected, everything works perfectly here.

Is there already an explanation or a solution to the problem?

Translated with DeepL.com (free version)
