### ISSUE TITLE
IsarError: DbError (1): no such index: FailedSendMessageDb_id 

### ISSUE THREAD

**Issue by Sansuihe** [isar/isar#1611]
### In the beginning, when I used the following classes to create and store data, it all worked

@collection
class FailedSendMessageDb{
  ///  消息id
  @Id()
  late final String msg_id;
  String? app_id;
  String? badge_mode;
  String? client_type;
  /// @Index()
  late String conversation_id;
  String? del_flag;
  String? from_id;
  String? from_name;
  String? from_photo;

  FailedSendMessageDb({
    required this.msg_id,
    this.app_id,
    this.badge_mode,
    this.client_type,
    required this.conversation_id,
    this.del_flag,
    this.from_id,
    this.from_name,
    this.from_photo,
  });
}

### I wanted to see what happened with @Index(), so I used @Index(), and I unwrapped the @Index() comment and regenerated it

flutter pub run build_runner build

### **But I tried to turn off @Index() again and regenerate the table**

/// @Index()
flutter pub run build_runner build

### When I started the project again, I got the following error message

I/flutter (14442): 出错：error==>,IsarError: DbError (1): no such index: FailedSendMessageDb_id 
I/flutter (14442):  出错：stack==>,#0      _extension#14.throwError (package:isar/src/impl/native_error.dart:32:11)
I/flutter (14442): #1      _extension#14.checkNoError (package:isar/src/impl/native_error.dart:7:7)
I/flutter (14442): #2      new _IsarImpl.open (package:isar/src/impl/isar_impl.dart:100:10)
I/flutter (14442): #3      Isar.open (package:isar/src/isar.dart:88:28)
I/flutter (14442): #4      DBTools.openDb (package:qi_an_xin/model_im/db_im/db_tools.dart:35:17)
I/flutter (14442): #5      DBTools.init (package:qi_an_xin/model_im/db_im/db_tools.dart:28:13)
I/flutter (14442): <asynchronous suspension>
I/flutter (14442): #6      UserState.init (package:qi_an_xin/model_im/provider_im/provider_user.dart:77:7)
I/flutter (14442): <asynchronous suspension>

### So I unwrapped the @Index() comment and regenerated it
flutter pub run build_runner build
### version
  isar: ^4.0.0-dev.14 
  isar_flutter_libs: ^4.0.0-dev.14
  build_runner: ^2.4.7

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.2, on macOS 14.0 23A344 darwin-arm64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.3)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2022.3)
[✓] VS Code (version 1.89.0)
[✓] Connected device (5 available)
[✓] Network resources

**Comment by Sansuihe** [comment]
### I seem to have found the correct trigger condition for the bug
### When I use sqlite to build a database the first time is always normal and then start again always prompt the above problem
### The startup mode is as follows

```
  Isar openDb(String path,String userId){
    return Isar.open(
      directory: path,
      schemas: [
        FailedSendMessageDbSchema,
        MessageJsonDbSchema
      ],
      name: userId,
      maxSizeMiB: 5000,
      engine: IsarEngine.sqlite,
      encryptionKey: "abc123",
    );
  }
```

I/flutter (14442): 出错：error==>,IsarError: DbError (1): no such index: FailedSendMessageDb_id
I/flutter (14442): 出错：stack==>,#0 _extension#14.throwError (package:isar/src/impl/native_error.dart:32:11)
I/flutter (14442): https://github.com/isar/isar/issues/1 _extension#14.checkNoError (package:isar/src/impl/native_error.dart:7:7)
I/flutter (14442): https://github.com/isar/isar/issues/2 new _IsarImpl.open (package:isar/src/impl/isar_impl.dart:100:10)
I/flutter (14442): https://github.com/isar/isar/issues/3 Isar.open (package:isar/src/isar.dart:88:28)
I/flutter (14442): https://github.com/isar/isar/issues/4 DBTools.openDb (package:qi_an_xin/model_im/db_im/db_tools.dart:35:17)
I/flutter (14442): https://github.com/isar/isar/issues/5 DBTools.init (package:qi_an_xin/model_im/db_im/db_tools.dart:28:13)
I/flutter (14442):
I/flutter (14442): https://github.com/isar/isar/issues/6 UserState.init (package:qi_an_xin/model_im/provider_im/provider_user.dart:77:7)
I/flutter (14442):

### But when I changed it to isar, this problem never came up again
```
  Isar openDb(String path,String userId){
    return Isar.open(
      directory: path,
      schemas: [
        FailedSendMessageDbSchema,
        MessageJsonDbSchema
      ],
      name: userId,
      maxSizeMiB: 5000,
      engine: IsarEngine.isar,
    );
  }
```
### But isar doesn't encrypt. I need to use sqlite's encryption
