### ISSUE TITLE
Failed to load dynamic library 'libisar.so'.

### ISSUE THREAD

**Issue by ashokavarthanan** [isar/isar#1629]
> **Note other device works fine.**

### Steps to Reproduce

```
E/flutter (13105): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: IsarNotReadyError: Could not initialize IsarCore library for processor architecture "android_arm". If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies. For Dart-only apps or unit tests, make sure to place the correct Isar binary in the correct directory.
E/flutter (13105): Invalid argument(s): Failed to load dynamic library 'libisar.so': dlopen failed: library "libisar.so" not found
E/flutter (13105): #0      initializePlatformBindings (package:isar/src/native/native.dart:26:5)
E/flutter (13105): #1      IsarCore._initialize (package:isar/src/isar_core.dart:42:20) 
E/flutter (13105): #2      new _IsarImpl.open (package:isar/src/impl/isar_impl.dart:50:14)
E/flutter (13105): #3      Isar.open (package:isar/src/isar.dart:88:28)
E/flutter (13105): #4      GlobalController.onInit (package:wdviewer/common/global.dart:126:17)
```

> pubspec.yaml

```
  isar: 4.0.0-dev.14
  isar_flutter_libs: ^4.0.0-dev.14
```

> GlobalController.onInit

```
isar = Isar.open(
  schemas: [MessageSchema],
  directory: appDocumentsDir.path,
  engine: IsarEngine.isar,
);
```

### Details

 - Platform: Samsung SM G600FY
 - Flutter version: 3.22.1
 - Isar version: 4.0.0-dev.14

```
[√] Flutter (Channel stable, 3.22.1, on Microsoft Windows [Version    
    10.0.19045.4412], locale en-IN)
    • Flutter version 3.22.1 on channel stable at C:\flutter
    • Upstream repository https://github.com/flutter/flutter.git      
    • Framework revision a14f74ff3a (3 weeks ago), 2024-05-22 11:08:21
      -0500
    • Engine revision 55eae6864b
    • Dart version 3.4.1
    • DevTools version 2.34.3

[√] Windows Version (Installed version of Windows is version 10 or
    higher)

[√] Android toolchain - develop for Android devices (Android SDK version    34.0.0)
    • Android SDK at C:\ANDROID_SDK_HOME\Sdk
    • Platform android-34, build-tools 34.0.0
    • Java binary at: C:\Program Files\Android\Android
      Studio\jbr\bin\java
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-b2043.56-10550314)
    • All Android licenses accepted.

[√] Chrome - develop for the web
    • Chrome at
      C:\Users\user\AppData\Local\Google\Chrome\Application\chrome.exe  

[!] Visual Studio - develop Windows apps (Visual Studio Build Tools 2019    16.11.25)
    • Visual Studio at C:\Program Files (x86)\Microsoft Visual
      Studio\2019\BuildTools
    • Visual Studio Build Tools 2019 version 16.11.33423.256
    X The current Visual Studio installation is incomplete.
      Please use Visual Studio Installer to complete the installation or      reinstall Visual Studio.

[√] Android Studio (version 2023.1)
    • Android Studio at C:\Program Files\Android\Android Studio
    • Flutter plugin can be installed from:
       https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
       https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build
      17.0.7+0-b2043.56-10550314)

[√] VS Code (version 1.90.0)
    • VS Code at C:\Users\user\AppData\Local\Programs\Microsoft VS Code 
    • Flutter extension version 3.90.0

[√] Connected device (4 available)
    • SM G600FY (mobile) • e03cb2bd • android-arm    • Android 6.0.1    
      (API 23)
    • Windows (desktop)  • windows  • windows-x64    • Microsoft Windows      [Version 10.0.19045.4412]
    • Chrome (web)       • chrome   • web-javascript • Google Chrome    
      125.0.6422.142
    • Edge (web)         • edge     • web-javascript • Microsoft Edge   
      125.0.2535.92

[√] Network resources
    • All expected network resources are available.
```
 - [ ] I searched for similar issues already
 - [ ] I filled the details section with the exact device model and version
 - [ ] I am able to provide a reproducible example

**Comment by ashokavarthanan** [comment]
I missed added to main()
`await Isar.initialize();`

solved.

**Comment by ashokavarthanan** [comment]
still i have problem.

**Comment by ashokavarthanan** [comment]
after 3hrs the problem is when I load `MobileAds.instance.initialize();` from `google_mobile_ads` .
When I removed `MobileAds.instance.initialize();` works fine Hot restart.

If I added `MobileAds.instance.initialize();`.
> First time I run.

```
W/Ads     ( 8993): Update ad debug logging enablement as false
W/        ( 8993): Unable to open '/system/framework/qcom.fmradio.jar': No such 
file or directory
W/art     ( 8993): Failed to open zip archive '/system/framework/qcom.fmradio.jar': I/O Error
W/        ( 8993): Unable to open '/system/framework/qcom.fmradio.jar': No such 
file or directory
W/art     ( 8993): Failed to open zip archive '/system/framework/qcom.fmradio.jar'
```

`I/flutter ( 8993): ║                   ISAR CONNECT STARTED  `

> when Hot restart

```
E/flutter ( 8993): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled 
Exception: IsarNotReadyError: Could not initialize IsarCore library for processor architecture "android_arm". If you create a Flutter app, make sure to add isar_flutter_libs to your dependencies. For Dart-only apps or unit tests, make sure 
to place the correct Isar binary in the correct directory.
E/flutter ( 8993): Invalid argument(s): Failed to load dynamic library 'libisar.so': dlopen failed: library "libisar.so" not found
E/flutter ( 8993): #0      initializePlatformBindings (package:isar/src/native/native.dart:26:5)
E/flutter ( 8993): #1      IsarCore._initialize (package:isar/src/isar_core.dart:42:20)
E/flutter ( 8993): #2      Isar.initialize (package:isar/src/isar.dart:35:21)   
```
What can I do?
How do I solve it?
Other devices work fine.
when I test with "SM G600FY (mobile) • android-arm • Android 6.0.1 (API 23)" 
I face a problem.

**Comment by ashleymorris2** [comment]
The project is dead. Give up

**Comment by lukecastronuevo** [comment]
I just encountered it earlier and I've found based on the previous issues that you need to change your minSdkVersion to 24. flutter clean then pub get. It's working on my end.

[Previous Issue](https://github.com/isar/isar/issues/831#issuecomment-1291225079)

**Comment by ashokavarthanan** [comment]
Thanks.
But I solved this issue another way. The problem is more then one instance app opening ( sharing intent package used).
So when app first opening it works fine. when another instance open via "sharing intent". so I got error.
I solved with error handler to user **close all opened app** alert.
without increasing Api 23 to 24.
