### ISSUE TITLE
isar ERROR

### ISSUE THREAD

**Issue by 461882111zzy** [isar/isar#1645]
### Steps to Reproduce

  isar: ^4.0.0-dev.14

[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid argument(s): Illegal argument in isolate message: object is unsendable - Library:'package:isar/isar.dart' Class: _IsarImpl@28212336 (see restrictions listed at `SendPort.send()` documentation for more information)
 <- field s in _MyHomePageState.initDB.<anonymous closure> (from package:slatool/main.dart)
 <- field callback in Isar.writeAsync.<anonymous closure> (from package:isar/isar.dart)
 <- field callback in _IsarImpl.writeAsyncWith.<anonymous closure> (from package:isar/isar.dart)
 <- resultPort in Instance of '_RemoteRunner<bool>' (from dart:isolate)

#0      Isolate._spawnFunction (dart:isolate-patch/isolate_patch.dart:398:25)
#1      Isolate.spawn (dart:isolate-patch/isolate_patch.dart:378:7)
#2      Isolate.run (dart:isolate:285:15)
#3      runIsolate (package:isar/src/native/native.dart:106:18)
#4      _IsarImpl.writeAsyncWith (package:isar/src/impl/isar_impl.dart:379:12)
#5      Isar.writeAsync (package:isar/src/isar.dart:243:7)
#6      _MyHomePageState.initDB (package:slatool/main.dart:201:7)

### Code sample

```dart
    Isar s = await Isar.openAsync(
        schemas: [EmailSchema], directory: '', engine: IsarEngine.sqlite);

    final email = Email()
      ..id = s.emails.autoIncrement()
      ..status = Status.draft
      ..title = 'xxxxxxx';

    s.writeAsync<bool>((_) {
      s.emails.put(email);
      return true;
    });
```

### Details

[✓] Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale zh-Hans-CN)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    ✗ cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    ✗ Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/macos#android-setup for more details.
[✓] Xcode - develop for iOS and macOS (Xcode 15.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] VS Code (version 1.90.1)

---

**Comment by kshatriyaArjunDeveloper** [comment]
Faced same issue

**Comment by Hilbert2048** [comment]
fixed,  https://github.com/isar/isar/issues/1393

**Comment by 461882111zzy** [comment]
when release this issue



发自我的iPhone


------------------ Original ------------------
From: hilbert ***@***.***&gt;
Date: Sun,Sep 1,2024 11:32 PM
To: isar/isar ***@***.***&gt;
Cc: zzy ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [isar/isar] isar ERROR (Issue #1645)





 
fixed,  #1393

**Comment by 0x01001** [comment]
same issue with isar v4.0.0-dev.14 flutter v3.22.3 :(
