### ISSUE TITLE
ios phone symbol not found

### ISSUE THREAD

**Issue by htsunshine** [isar/isar#169]
[VERBOSE-2:ui_dart_state.cc(209)] Unhandled Exception: Invalid argument(s): Failed to lookup symbol (dlsym(RTLD_DEFAULT, isar_connect_dart_api): symbol not found)
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:31:29)
#1      IsarCoreBindings._isar_connect_dart_api_ptr (package:isar/src/native/bindings.dart:332:60)
#2      IsarCoreBindings._isar_connect_dart_api_ptr (package:isar/src/native/bindings.dart)
#3      IsarCoreBindings._isar_connect_dart_api (package:isar/src/native/bindings.dart:335:7)
#4      IsarCoreBindings._isar_connect_dart_api (package:isar/src/native/bindings.dart)
#5      IsarCoreBindings.isar_connect_dart_api (package:isar/src/native/bindings.dart:326:12)
#6      openIsarNative (package:isar/src/native/open.dart:26:6)
<asynchronous suspension>

**Version**
 - Platform: iOS
 - Flutter version: [e.g. 2.14.3]
 - Isar version: 1.0.5
 - Isar Generator version: [e.g.1.0.5]

**Comment by rizzi37** [comment]
#144

**Comment by leisim** [comment]
Please use `isar_flutter_libs: ^1.0.5` and Run `flutter clean`.

**Comment by htsunshine** [comment]
Ios Debug mode can be initialized, but release mode fails to be initialized.
