### ISSUE TITLE
Isar inspector on android device not able to connect

### ISSUE THREAD

**Issue by jackdy19** [isar/isar#203]
**Steps to Reproduce**
Hi, I am trying to connect to the isar inspector, but it is throwing this error after I paste the URL to connect:
**Code sample**
```
flutter: isolates/2178546262321779
flutter: ERROR: Unable to connect to VMService
flutter: ext.isar.getSchema: (-32000) Server error
Null check operator used on a null value
flutter: #0      new _OutstandingRequest (package:vm_service/src/vm_service.dart:1718:45)
#1      VmService._call (package:vm_service/src/vm_service.dart:2225:21)
#2      VmService.callServiceExtension (package:vm_service/src/vm_service.dart:2190:14)
#3      Service._call (package:isar_inspector/service.dart:38:35)
#4      Service.getSchema (package:isar_inspector/service.dart:50:40)
#5      _ConnectPageState._connect (package:isar_inspector/connect.dart:26:40)
<asynchronous suspension>

```

I thought the isolate Id would be null, but it is not the case as printed also above. Can sb please point me in the right direction what could be the issue?

**Version**
 - Platform: Android, Mac
 - Flutter version: 2.8.1
 - Isar version: 2.0.0
 - Isar Generator version: 2.0.0

**Comment by JsonLinesCode** [comment]
I am getting the `ext.isar.getVersion: (-32601) Unknown method "ext.isar.getVersion".` from #46 on both windows and macos

**Comment by JPM84** [comment]
Similar issue here. Happens also when build from source.
But was able to connect after realizing that **/ws** is missing in the url. `ws://127.0.0.1:58955/MY_TOKEN/ws`.
```
flutter: ERROR: Unable to connect to VMService
flutter: WebSocketException: Connection to 'http://127.0.0.1:58955/uM9abaF9Fd0=/#' was not upgraded to websocket
flutter: #0      _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1011:41)
#1      WebSocket.connect (dart:_http/websocket.dart:360:22)
#2      vmServiceConnectUri (package:vm_service/vm_service_io.dart:32:44)
#3      Service.connect (package:isar_inspector/service.dart:18:29)
#4      _ConnectPageState._connect (package:isar_inspector/connect.dart:24:37)
```

**Comment by leisim** [comment]
Should be fixed with the new inspector
