### ISSUE TITLE
Error Occurs When Try to run flutter build apk

### ISSUE THREAD

**Issue by anandsubbu007** [isar/isar#214]
Problems Occurs When 'Isar.open()' function runs.

```
import 'dart:io';
import 'package:flutter/material.dart';
import 'dart:async';
import 'package:isar/isar.dart';
import 'package:path_provider/path_provider.dart' as pth;

void main() async {
  runApp(const AndroidAppInit());
}

class AndroidAppInit extends StatelessWidget {
  const AndroidAppInit({Key? key}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    Future redisterdb() async {
      Directory dir = await pth.getApplicationDocumentsDirectory();
      await Isar.open(schemas: [AppUserSchema], directory: dir.path);
    }

    return FutureBuilder(
      future: redisterdb(),
      builder: (ctx, snap) {
        return const Scaffold(body: Text('Teting'));
      },
    );
  }
}

@Collection()
class AppUser {
  @Id()
  int? index;
  String? name;
  AppUser({this.index, this.name = ''});
}
```

```
environment:
  sdk: ">=2.16.0-134.1.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  isar: ^2.1.0
  isar_flutter_libs: ^2.1.0
  path_provider: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  isar_generator: ^2.1.0
```

An Error occurs in External Library only on Android Build. 
Working fines in Windows Build

```
flutter build apk --release --verbose
[  +95 ms] executing: [C:\My Program Setup\Flutter Components\Flutter Dev\flutter/] git -c log.showSignature=false log -n 1 --pretty=format:%H
[ +606 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +2 ms] 73adb1406a9cff796e2203ad16fd285220a6ec97
[   +1 ms] executing: [C:\My Program Setup\Flutter Components\Flutter Dev\flutter/] git tag --points-at 73adb1406a9cff796e2203ad16fd285220a6ec97
[  +81 ms] Exit code 0 from: git tag --points-at 73adb1406a9cff796e2203ad16fd285220a6ec97
[        ] 2.10.0-0.2.pre
[  +16 ms] executing: [C:\My Program Setup\Flutter Components\Flutter Dev\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[  +54 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[        ] origin/beta
[        ] executing: [C:\My Program Setup\Flutter Components\Flutter Dev\flutter/] git ls-remote --get-url origin
[  +51 ms] Exit code 0 from: git ls-remote --get-url origin
[        ] https://github.com/flutter/flutter.git
[ +153 ms] executing: [C:\My Program Setup\Flutter Components\Flutter Dev\flutter/] git rev-parse --abbrev-ref HEAD
[  +65 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[        ] beta
[  +73 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +8 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.       
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.     
[   +1 ms] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.     
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.    
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +146 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[  +18 ms] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +6 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[ +193 ms] Skipping pub get: version match.
[  +91 ms] Found plugin isar_flutter_libs at C:\My Program Setup\Flutter Components\Flutter
Dev\flutter\.pub-cache\hosted\pub.dartlang.org\isar_flutter_libs-2.1.0\
[  +36 ms] Found plugin path_provider at C:\My Program Setup\Flutter Components\Flutter
Dev\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.8\
[   +3 ms] Found plugin path_provider_android at C:\My Program Setup\Flutter Components\Flutter
Dev\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_android-2.0.11\
[   +6 ms] Found plugin path_provider_ios at C:\My Program Setup\Flutter Components\Flutter
Dev\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_ios-2.0.7\
[   +6 ms] Found plugin path_provider_linux at C:\My Program Setup\Flutter Components\Flutter
Dev\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.1.5\
[   +2 ms] Found plugin path_provider_macos at C:\My Program Setup\Flutter Components\Flutter
Dev\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.5\
[   +6 ms] Found plugin path_provider_windows at C:\My Program Setup\Flutter Components\Flutter
Dev\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.5\
[ +137 ms] Found plugin isar_flutter_libs at C:\My Program Setup\Flutter Components\Flutter
Dev\flutter\.pub-cache\hosted\pub.dartlang.org\isar_flutter_libs-2.1.0\
[  +11 ms] Found plugin path_provider at C:\My Program Setup\Flutter Components\Flutter
Dev\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider-2.0.8\
[   +3 ms] Found plugin path_provider_android at C:\My Program Setup\Flutter Components\Flutter
Dev\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_android-2.0.11\
[   +2 ms] Found plugin path_provider_ios at C:\My Program Setup\Flutter Components\Flutter
Dev\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_ios-2.0.7\
[   +2 ms] Found plugin path_provider_linux at C:\My Program Setup\Flutter Components\Flutter
Dev\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_linux-2.1.5\
[   +3 ms] Found plugin path_provider_macos at C:\My Program Setup\Flutter Components\Flutter
Dev\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_macos-2.0.5\
[   +4 ms] Found plugin path_provider_windows at C:\My Program Setup\Flutter Components\Flutter
Dev\flutter\.pub-cache\hosted\pub.dartlang.org\path_provider_windows-2.0.5\
[  +51 ms] Generating
C:\Users\anand\Desktop\Github\flutter_native_opencv-master\demo\android\app\src\main\java\io\flutter\plugins\GeneratedPluginRegistrant.java
[ +134 ms]  Building with sound null safety 
[  +29 ms] Running Gradle task 'assembleRelease'...
[   +9 ms] Using gradle from C:\Users\anand\Desktop\Github\flutter_native_opencv-master\demo\android\gradlew.bat.
[  +24 ms] executing: C:\My Program Setup\Flutter Components\Android Studio\jre\bin\java -version
[ +186 ms] Exit code 0 from: C:\My Program Setup\Flutter Components\Android Studio\jre\bin\java -version
[        ] openjdk version "1.8.0_212-release"
           OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
           OpenJDK 64-Bit Server VM (build 25.212-b04, mixed mode)
[   +5 ms] executing: [C:\Users\anand\Desktop\Github\flutter_native_opencv-master\demo\android/]
C:\Users\anand\Desktop\Github\flutter_native_opencv-master\demo\android\gradlew.bat -Pverbose=true
-Ptarget-platform=android-arm,android-arm64,android-x64 -Ptarget=lib\main.dart -Pbase-application-name=android.app.Application -Pdart-obfuscation=false-Ptrack-widget-creation=true -Ptree-shake-icons=true assembleRelease
[+4606 ms] > Task :app:compileFlutterBuildRelease
[   +1 ms] [  +80 ms] executing: [C:\My Program Setup\Flutter Components\Flutter Dev\flutter/] git -c log.showSignature=false log -n 1
--pretty=format:%H
[   +4 ms] [ +643 ms] Exit code 0 from: git -c log.showSignature=false log -n 1 --pretty=format:%H
[   +1 ms] [        ] 73adb1406a9cff796e2203ad16fd285220a6ec97
[   +1 ms] [        ] executing: [C:\My Program Setup\Flutter Components\Flutter Dev\flutter/] git tag --points-at
73adb1406a9cff796e2203ad16fd285220a6ec97
[   +2 ms] [  +68 ms] Exit code 0 from: git tag --points-at 73adb1406a9cff796e2203ad16fd285220a6ec97
[   +1 ms] [        ] 2.10.0-0.2.pre
[   +1 ms] [  +23 ms] executing: [C:\My Program Setup\Flutter Components\Flutter Dev\flutter/] git rev-parse --abbrev-ref --symbolic @{u}
[   +1 ms] [  +63 ms] Exit code 0 from: git rev-parse --abbrev-ref --symbolic @{u}
[   +6 ms] [        ] origin/beta
[   +4 ms] [        ] executing: [C:\My Program Setup\Flutter Components\Flutter Dev\flutter/] git ls-remote --get-url origin
[   +2 ms] [  +66 ms] Exit code 0 from: git ls-remote --get-url origin
[   +1 ms] [        ] https://github.com/flutter/flutter.git
[   +8 ms] [  +72 ms] executing: [C:\My Program Setup\Flutter Components\Flutter Dev\flutter/] git rev-parse --abbrev-ref HEAD
[   +4 ms] [  +49 ms] Exit code 0 from: git rev-parse --abbrev-ref HEAD
[   +1 ms] [        ] beta
[   +1 ms] [  +59 ms] Artifact Instance of 'AndroidGenSnapshotArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [   +4 ms] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[        ] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[ +223 ms] [ +228 ms] Artifact Instance of 'MaterialFonts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'GradleWrapper' is not required, skipping update.
[   +2 ms] [   +4 ms] Artifact Instance of 'AndroidInternalBuildArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'IOSEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'FlutterWebSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterSdk' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'WindowsEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'WindowsUwpEngineArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'MacOSEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxEngineArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'LinuxFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'MacOSFuchsiaSDKArtifacts' is not required, skipping update.
[   +1 ms] [        ] Artifact Instance of 'FlutterRunnerSDKArtifacts' is not required, skipping update.
[   +3 ms] [        ] Artifact Instance of 'FlutterRunnerDebugSymbols' is not required, skipping update.
[  +10 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[  +20 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'IosUsbArtifacts' is not required, skipping update.
[   +7 ms] [        ] Artifact Instance of 'FontSubsetArtifacts' is not required, skipping update.
[   +2 ms] [        ] Artifact Instance of 'PubDependencies' is not required, skipping update.
[  +19 ms] [ +126 ms] Initializing file store
[   +1 ms] [  +38 ms] Done initializing file store
[ +297 ms] [ +272 ms] Skipping target: gen_localizations
[        ] [  +18 ms] Skipping target: gen_dart_plugin_registrant
[ +711 ms] [ +714 ms] Skipping target: kernel_snapshot
[   +1 ms] [   +3 ms] android_aot_release_android-arm: Starting due to {}
[  +91 ms] [   +8 ms] executing: C:\My Program Setup\Flutter Components\Flutter
Dev\flutter\bin\cache\artifacts\engine\android-arm-release\windows-x64\gen_snapshot --deterministic --snapshot_kind=app-aot-elf
--elf=C:\Users\anand\Desktop\Github\flutter_native_opencv-master\demo\.dart_tool\flutter_build\c1f522729a8888c0ec1c066966be0412\armeabi-v7a\app.so     
--strip --no-sim-use-hardfp --no-use-integer-division
C:\Users\anand\Desktop\Github\flutter_native_opencv-master\demo\.dart_tool\flutter_build\c1f522729a8888c0ec1c066966be0412\app.dill
[   +3 ms] [  +77 ms] aot_android_asset_bundle: Starting due to {InvalidatedReasonKind.inputChanged: The following inputs have updated contents:
C:\Users\anand\Desktop\Github\flutter_native_opencv-master\demo\pubspec.yaml}
[  +90 ms] [  +38 ms] Skipping target: android_aot_release_android-arm64
[   +1 ms] [  +17 ms] Skipping target: android_aot_release_android-x64
[ +421 ms] [ +393 ms] Running command: C:\My Program Setup\Flutter Components\Flutter Dev\flutter\bin\cache\dart-sdk\bin\dart.exe --disable-dart-dev
C:\My Program Setup\Flutter Components\Flutter Dev\flutter\bin\cache\artifacts\engine\windows-x64\const_finder.dart.snapshot --kernel-file
C:\Users\anand\Desktop\Github\flutter_native_opencv-master\demo\.dart_tool\flutter_build\c1f522729a8888c0ec1c066966be0412\app.dill --class-library-uri 
package:flutter/src/widgets/icon_data.dart --class-name IconData
[ +989 ms] [+1035 ms] aot_android_asset_bundle: Complete
[  +93 ms] [  +78 ms] Skipping target: android_aot_bundle_release_android-arm64
[        ] [  +30 ms] Skipping target: android_aot_bundle_release_android-x64
[+1900 ms] [+1866 ms] ../../third_party/dart/runtime/vm/compiler/aot/precompiler.cc: 3298: error: unreachable code
[ +597 ms] [   +3 ms] Persisting file store
[   +1 ms] [  +15 ms] Done persisting file store
[   +1 ms] [ +589 ms] Dart snapshot generator failed with exit code -1073740791
[        ] [  +14 ms] Target android_aot_release_android-arm failed: Exception: AOT snapshotter exited with code -1073740791
[   +1 ms]            #0      AndroidAot.build (package:flutter_tools/src/build_system/targets/android.dart:257:7)
[   +1 ms]            <asynchronous suspension>
[   +1 ms]            #1      _BuildInstance._invokeInternal (package:flutter_tools/src/build_system/build_system.dart:839:9)
[        ]            <asynchronous suspension>
[        ]            #2      Future.wait.<anonymous closure> (dart:async/future.dart:473:21)
[        ]            <asynchronous suspension>
[        ]            #3      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:777:32)
[        ]            <asynchronous suspension>
[        ]            #4      Future.wait.<anonymous closure> (dart:async/future.dart:473:21)
[        ]            <asynchronous suspension>
[   +1 ms]            #5      _BuildInstance.invokeTarget (package:flutter_tools/src/build_system/build_system.dart:777:32)
[        ]            <asynchronous suspension>
[   +1 ms]            #6      FlutterBuildSystem.build (package:flutter_tools/src/build_system/build_system.dart:606:16)
[   +1 ms]            <asynchronous suspension>
[   +1 ms]            #7      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:317:32)
[   +1 ms]            <asynchronous suspension>
[        ]            #8      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
[        ]            <asynchronous suspension>
[        ]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #10     CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[        ]            <asynchronous suspension>
[   +1 ms]            #11     FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9) 
[   +1 ms]            <asynchronous suspension>
[   +1 ms]            #12     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[   +1 ms]            <asynchronous suspension>
[   +1 ms]            #13     FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
[   +1 ms]            <asynchronous suspension>
[   +1 ms]            #14     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[   +1 ms]            <asynchronous suspension>
[        ]            #15     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #16     main (package:flutter_tools/executable.dart:94:3)
[   +1 ms]            <asynchronous suspension>
[   +2 ms] [   +6 ms] 
[   +1 ms]            #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
[   +2 ms]            #1      AssembleCommand.runCommand (package:flutter_tools/src/commands/assemble.dart:334:7)
[        ]            <asynchronous suspension>
[        ]            #2      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
[        ]            <asynchronous suspension>
[        ]            #3      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[        ]            #4      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
[   +1 ms]            <asynchronous suspension>
[   +1 ms]            #5      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9) 
[   +1 ms]            <asynchronous suspension>
[   +1 ms]            #6      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[        ]            <asynchronous suspension>
[   +1 ms]            #7      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
[   +1 ms]            <asynchronous suspension>
[   +1 ms]            #8      run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
[   +1 ms]            <asynchronous suspension>
[   +1 ms]            #9      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
[   +2 ms]            <asynchronous suspension>
[   +2 ms]            #10     main (package:flutter_tools/executable.dart:94:3)
[   +1 ms]            <asynchronous suspension>
[   +1 ms] [  +15 ms] "flutter assemble" took 5,603ms.
[ +238 ms] [ +254 ms] ensureAnalyticsSent: 253ms
[   +6 ms] [   +1 ms] Running shutdown hooks
[   +2 ms] [        ] Shutdown hooks complete
[   +3 ms] [        ] exiting with code 1
[  +11 ms] > Task :app:compileFlutterBuildRelease FAILED
[   +1 ms] FAILURE: Build failed with an exception.
[   +3 ms] * Where:
[  +56 ms] Script 'C:\My Program Setup\Flutter Components\Flutter Dev\flutter\packages\flutter_tools\gradle\flutter.gradle' line: 1102
[   +2 ms] * What went wrong:
[   +7 ms] Execution failed for task ':app:compileFlutterBuildRelease'.
[   +1 ms] > Process 'command 'C:\My Program Setup\Flutter Components\Flutter Dev\flutter\bin\flutter.bat'' finished with non-zero exit value 1        
[   +1 ms] * Try:
[        ] Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full  
insights.
[   +1 ms] * Get more help at https://help.gradle.org
[   +3 ms] Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
[   +1 ms] Use '--warning-mode all' to show the individual deprecation warnings.
[   +1 ms] See https://docs.gradle.org/6.7/userguide/command_line_interface.html#sec:command_line_warnings
[   +1 ms] 1 actionable task: 1 executed
[   +1 ms] BUILD FAILED in 10s
[ +511 ms] Running Gradle task 'assembleRelease'... (completed in 11.3s)
[   +6 ms] "flutter apk" took 12,304ms.
[   +5 ms] Gradle task assembleRelease failed with exit code 1
[   +1 ms] 
           #0      throwToolExit (package:flutter_tools/src/base/common.dart:10:3)
           #1      AndroidGradleBuilder.buildGradleApp (package:flutter_tools/src/android/gradle.dart:400:9)
           <asynchronous suspension>
           #2      AndroidGradleBuilder.buildApk (package:flutter_tools/src/android/gradle.dart:179:5)
           <asynchronous suspension>
           #3      BuildApkCommand.runCommand (package:flutter_tools/src/commands/build_apk.dart:112:5)
           <asynchronous suspension>
           #4      FlutterCommand.run.<anonymous closure> (package:flutter_tools/src/runner/flutter_command.dart:1161:27)
           <asynchronous suspension>
           #5      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #6      CommandRunner.runCommand (package:args/command_runner.dart:209:13)
           <asynchronous suspension>
           #7      FlutterCommandRunner.runCommand.<anonymous closure> (package:flutter_tools/src/runner/flutter_command_runner.dart:281:9)
           <asynchronous suspension>
           #8      AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #9      FlutterCommandRunner.runCommand (package:flutter_tools/src/runner/flutter_command_runner.dart:229:5)
           <asynchronous suspension>
           #10     run.<anonymous closure>.<anonymous closure> (package:flutter_tools/runner.dart:62:9)
           <asynchronous suspension>
           #11     AppContext.run.<anonymous closure> (package:flutter_tools/src/base/context.dart:150:19)
           <asynchronous suspension>
           #12     main (package:flutter_tools/executable.dart:94:3)
           <asynchronous suspension>


[ +198 ms] ensureAnalyticsSent: 191ms
[   +2 ms] Running shutdown hooks
[   +1 ms] Shutdown hooks complete
[   +1 ms] exiting with code 1
```

**Comment by leisim** [comment]
This looks more like a Flutter problem than an Isar bug 🤔

Did you try `flutter clean`? Did you try running the quotes sample app?

**Comment by anandsubbu007** [comment]
https://github.com/flutter/flutter/issues/97301#issue-1115267025

yep i tried it after `flutter clean`

**Comment by simonpham** [comment]
@anandsubbu007 
> C:\My Program Setup\Flutter Components\Flutter Dev\flutter

You should not place flutter in the path that contains space characters like that.
Try moving it to C:\Dev\flutter to see if the issue is gone

**Comment by anandsubbu007** [comment]
> 

Still Facing This Issue.

**Comment by anandsubbu007** [comment]
> @anandsubbu007
> 
> > C:\My Program Setup\Flutter Components\Flutter Dev\flutter
> 
> You should not place flutter in the path that contains space characters like that. Try moving it to C:\Dev\flutter to see if the issue is gone

Still Facing the same Issue

**Comment by leisim** [comment]
Unfortunately I still cannot reproduce it :(

**Comment by anandsubbu007** [comment]
there is an issue with flutter not being in isar package.
`Flutter AOT precompiler crash using isar package.`
I believe that they were working on it.

**Comment by leisim** [comment]
Going to close this because the flutter bug is fixed :)
