### ISSUE TITLE
`offset < _staticSize: is not true` after migration

### ISSUE THREAD

**Issue by talesbarreto** [isar/isar#235]
Hi there.
I'm considering using Isar in a new project. I have traumatic experiences with DB migrations in previous projects so I'm trying to do some experiments to see how well Isar can handler with that.

I read the [doc](https://isar.dev/schema.html#schema-migration). it tells what can and can not do on schema migrations and nothing else. I assumed that there is nothing to be done: I can simply edit my collections, respecting those rules, and everything will just work, am I right?

So, I simulated a scenario that I would delete a String field and add a new one (in reality, I  just renamed it)

**Steps to Reproduce**
- Create a collection with two **int**s  and three **String**s
- `dart run build_runner build`
- Run my app
- Save an entry to my collection

- Renamed the second String
- `dart run build_runner build`
- Run my app
- Read the previous saved entry
- Edit all fields but the id 
- Save the entry to my collection -> crash

StackTrace
```
E/flutter (26175): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: 'package:isar/src/native/binary_writer.dart': Failed assertion: line 84 pos 12: 'offset < _staticSize': is not true.
E/flutter (26175): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (26175): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (26175): #2      BinaryWriter.writeBytes (package:isar/src/native/binary_writer.dart:84:12)
E/flutter (26175): #3      _MyStateAdapter.serialize (package:playground/my_state/my_state.g.dart:67:12)
E/flutter (26175): #4      IsarCollectionImpl.putAll.<anonymous closure> (package:isar/src/native/isar_collection_impl.dart:198:17)
E/flutter (26175): #5      IsarCollectionImpl.putAll.<anonymous closure> (package:isar/src/native/isar_collection_impl.dart:190:30)
E/flutter (26175): #6      IsarImpl.getTxn (package:isar/src/native/isar_impl.dart:100:22)
E/flutter (26175): #7      IsarCollectionImpl.putAll (package:isar/src/native/isar_collection_impl.dart:190:17)
E/flutter (26175): #8      IsarCollection.put (package:isar/src/isar_collection.dart:48:12)
E/flutter (26175): #9      _MyHomePageState.storeMyState.<anonymous closure> (package:playground/main.dart:71:50)
E/flutter (26175): #10     IsarImpl._txn.<anonymous closure> (package:isar/src/native/isar_impl.dart:66:45)
E/flutter (26175): #11     _rootRun (dart:async/zone.dart:1426:13)
E/flutter (26175): #12     _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (26175): #13     IsarImpl._txn (package:isar/src/native/isar_impl.dart:66:27)
E/flutter (26175): <asynchronous suspension>
E/flutter (26175): #14     _MyHomePageState._incrementCounter (package:playground/main.dart:80:5)
E/flutter (26175): <asynchronous suspension>
E/flutter (26175): 
```

**Code sample**
First Collection:

```dart
@Collection()
class MyState {
  int id;

  int number;

  String numberText3;
  String numberText2;
  String numberText1;

  MyState({
    required this.id,
    this.number = 0,
    this.numberText3 = "Default Value",
    this.numberText2 = "Default Value",
    this.numberText1 = "Default Value",
  });
}
```
Second collection
```dart
@Collection()
class MyState {
  int id;

  int number;

  String numberText3;
  String numberText22;
  String numberText1;

  MyState({
    required this.id,
    this.number = 0,
    this.numberText3 = "Default Value",
    this.numberText22 = "Default Value",
    this.numberText1 = "Default Value",
  });
}
```
Did I get it wrong about the migration process or this is really a bug?

Thanks a lot.

**Version**
 - Platform: Android and Mac
 - Flutter version:  2.10.1
 - Isar version: 2.1.4
 - Isar Generator version: 2.1.4

**Comment by leisim** [comment]
A new Isar version will be released today or tomorrow :)

**Comment by leisim** [comment]
Released!
