### ISSUE TITLE
App crashes when setting a backlink manually 

### ISSUE THREAD

**Issue by volund** [isar/isar#272]
**Steps to Reproduce**
I do not currently have a minimal example that reproduces the crash. It crashes repeatedly in large app, and the cause seems to be me setting a backlink's value (unnecessarily). I have tried to reproduce the issue with a minimal example but so far have been unable to.

However this is the stacktrace I get with GDB:

```
    thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', src/txn.rs:118:56
    note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
    fatal runtime error: failed to initiate panic, error 5
    
    Thread 8 "io.flutter.ui" received signal SIGABRT, Aborted.
    [Switching to Thread 0x7fffe8c71700 (LWP 684659)]
    __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
    50	../sysdeps/unix/sysv/linux/raise.c: No such file or directory.
    (gdb) bt
    #0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
    #1  0x00007ffff4442859 in __GI_abort () at abort.c:79
    #2  0x00007fff9dc701b7 in  () at /tmp/project/app/build/linux/x64/debug/bundle/lib/libisar.so
    #3  0x00007fff9dc7012f in  () at /tmp/project/app/build/linux/x64/debug/bundle/lib/libisar.so
    #4  0x00007fff9dc6fc82 in  () at /tmp/project/app/build/linux/x64/debug/bundle/lib/libisar.so
    #5  0x00007fff9dc912a8 in  () at /tmp/project/app/build/linux/x64/debug/bundle/lib/libisar.so
    #6  0x00007fff9dc91226 in  () at /tmp/project/app/build/linux/x64/debug/bundle/lib/libisar.so
    #7  0x00007fff9dc911e2 in  () at /tmp/project/app/build/linux/x64/debug/bundle/lib/libisar.so
    #8  0x00007fff9dbaa000 in  () at /tmp/project/app/build/linux/x64/debug/bundle/lib/libisar.so
    #9  0x00007fff9dbaa2d2 in  () at /tmp/project/app/build/linux/x64/debug/bundle/lib/libisar.so
    #10 0x00007fff9dc12d85 in  () at /tmp/project/app/build/linux/x64/debug/bundle/lib/libisar.so
    #11 0x00007fff9dc0ac76 in isar_put_all () at /tmp/project/app/build/linux/x64/debug/bundle/lib/libisar.so
```

And this is the stack trace I get when running with `RUST_BACKTRACE=full`:

```
    thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: SendError { .. }', src/txn.rs:118:56
    stack backtrace:
       0:     0x7f5e7b4f14fd - <unknown>
       1:     0x7f5e7b496c0c - <unknown>
       2:     0x7f5e7b4eff44 - <unknown>
       3:     0x7f5e7b4f0640 - <unknown>
       4:     0x7f5e7b4efa31 - <unknown>
       5:     0x7f5e7b5112a8 - <unknown>
       6:     0x7f5e7b511226 - <unknown>
       7:     0x7f5e7b5111e2 - <unknown>
       8:     0x7f5e7b42a000 - <unknown>
       9:     0x7f5e7b42a2d2 - <unknown>
      10:     0x7f5e7b492d85 - <unknown>
      11:     0x7f5e7b48ac76 - isar_put_all
      12:     0x7f5ea420598b - <unknown>
    fatal runtime error: failed to initiate panic, error 5
    Aborted (core dumped)
```

**Code sample**
N/A

**Version**
 - Platform: Linux
 - Flutter version: 2.10.2
 - Isar version: 2.2.0
 - Isar Generator version: 2.2.0

**Comment by volund** [comment]
Is there a way for me to (further) symbolicate the crash report?

**Comment by leisim** [comment]
This should be fixed :+1:
