### ISSUE TITLE
Guid support

### ISSUE THREAD

**Issue by alimcomp** [isar/isar#405]
Hello
And thanks in advance
In our project we need guid as id of our collection

**Comment by etiennelenhart** [comment]
Does this actually work?

I tried using a ULID from the _ulid_ package as a unique index like so:
```dart
@Index(unique: true)
@UlidConverter()
Ulid ulid;
```
```dart
class UlidConverter extends TypeConverter<Ulid, String> {
  const UlidConverter();

  @override
  Ulid fromIsar(String object) => Ulid.parse(object);

  @override
  String toIsar(Ulid object) => object.toString();
}
```
`put` and `get` do seem to work properly but `getByUlid` fails with "_CastError (type 'Ulid' is not a subtype of type 'String?' in type cast)"

**Comment by spatialbits** [comment]
I can reproduce, don't really know what's causing it, may be a bug. The stack trace is:
```
E/flutter (20172): [ERROR:flutter/lib/ui/ui_dart_state.cc(209)] Unhandled Exception: type 'Ulid' is not a subtype of type 'String?' in type cast
E/flutter (20172): #0      _addKeyValue
package:isar/…/native/index_key.dart:73
E/flutter (20172): #1      buildIndexKey
package:isar/…/native/index_key.dart:23
E/flutter (20172): #2      IsarCollectionImpl._getKeysPtr
package:isar/…/native/isar_collection_impl.dart:82
E/flutter (20172): #3      IsarCollectionImpl.getAllByIndex.<anonymous closure>
package:isar/…/native/isar_collection_impl.dart:151
E/flutter (20172): #4      IsarCollectionImpl.getAllByIndex.<anonymous closure>
package:isar/…/native/isar_collection_impl.dart:149
E/flutter (20172): #5      IsarImpl.getTxn.<anonymous closure>
package:isar/…/native/isar_impl.dart:97
E/flutter (20172): #6      IsarImpl._txn.<anonymous closure>
package:isar/…/native/isar_impl.dart:60
E/flutter (20172): #7      _rootRun (dart:async/zone.dart:1426:13)
E/flutter (20172): #8      _CustomZone.run (dart:async/zone.dart:1328:19)
E/flutter (20172): #9      IsarImpl._txn
package:isar/…/native/isar_impl.dart:60
```

I don't use the generated query methods, eg `getByUlid()` etc., I construct my queries. When I manually construct the query I am able to fetch the model using the `ulid` property with the type converter doing its thing:

You can give your index a `name` value:
```
  @Index(unique: true, name: 'ulidIdx')
  @UlidConverter()
  late Ulid ulid;
```

And then use that to build the query:
```
    final q = col.buildQuery<SomeModel>(
        whereClauses: [asString(s1!.ulid.toCanonical())]);
    final s2 = await q.findFirst();
```

Also, I'm not so familiar with `Ulid`, but you may want to take a closer look at `.toString()` vs `.toCanonical()`.

**Comment by leisim** [comment]
Could be a bug. I'll take a look!

**Comment by etiennelenhart** [comment]
I think it just may be a bug with the generated `get` methods not using the type converter. Also having to use a String when building the index query doesn't seem quite right, but I guess that's to be expected because of the more generic nature of `buildQuery()`.

`toString()` simply calls `toCanonical()` so that shouldn't be a problem.

**Comment by etiennelenhart** [comment]
Oh wow… will there be an alternative for type converters? As far as I understand @Embedded might be used in the future?

But what about UUID/ULID keys?

**Comment by leisim** [comment]
Yeah the alternative is something like this:

```dart
@collection
class TestModel {
  Id? id;

  String? uuidStr;

  @ignore
  UUID get uuid => UUID(uuidStr);
}
```

**Comment by etiennelenhart** [comment]
So I‘d basically write my own converter code? Less than ideal, but I guess it‘ll work.
Any particular reason to remove type converters? I normally consider these more or less mandatory for ORM based libraries.

**Comment by leisim** [comment]
The reason is that they are not really needed any more. The main use case were embedded objects and enums.

The newest Isar version has a significantly improved insert performance (up to 50%) which is quite an achievement since Isar was already faster than all competitors. This speed improvement only works without type converters however because Isar needs to be able to estimate the size of the value which is not really possible with type converters.

Also type converters had weird edge cases with queries.

I repeated this many times but I recommend to just store uuids as strings in Isar.

**Comment by etiennelenhart** [comment]
Cool, sounds reasonable. „Sacrificing“ some convenience for larger performance gains seems perfectly fine.
It doesn’t quite match my use case but I‘m still impressed where Isar is heading.
Thanks for the clarification.

**Comment by leisim** [comment]
@etiennelenhart I'd love to hear more about your use case. Would you mind giving a small example? Maybe we can find an improvement for the next version 🙂

**Comment by etiennelenhart** [comment]
Nothing special. I evaluated Isar as a local database to sync with Firestore for better diffing and concurrent multi-user edits.
That‘s why I basically always want to use ULIDs for all IDs.

The app won‘t work with a lot of data so performance isn‘t one of my concerns and some convenience APIs for working with DTOs are more important.

So no particular ideas for improvement. Still looking forward to Isar’s sync solution.
