### ISSUE TITLE
Error: Unsupported operation: dart:isolate is not supported on dart4web

### ISSUE THREAD

**Issue by gaganyadav80** [isar/isar#410]
**Steps to Reproduce**
When I try to run my flutter app on web then `Isar.open` throws error `Error: Unsupported operation: dart:isolate is not supported on dart4web` (check attached file for full logs). It works perfectly on mobile device but on web throws error.
When I comment out the `Isar.open()` call then there is no error shown.

**Error**
```bash
[  +12 ms] Error: Unsupported operation: dart:isolate is not supported on dart4web
               at Object.throw_ [as throw] (http://localhost:58060/dart_sdk.js:5080:11)
               at Object._unsupported (http://localhost:58060/dart_sdk.js:61790:15)
               at RawReceivePort.new (http://localhost:58060/dart_sdk.js:61717:23)
               at getInfo (http://localhost:58060/dart_sdk.js:51742:54)
               at getInfo.next (<anonymous>)
               at runBody (http://localhost:58060/dart_sdk.js:40660:34)
               at Object._async [as async] (http://localhost:58060/dart_sdk.js:40691:7)
               at Service.getInfo (http://localhost:58060/dart_sdk.js:51741:20)
               at Object._initializeIsarConnect (http://localhost:58060/packages/isar/src/web/open.dart.lib.js:4631:23)
               at http://localhost:58060/packages/isar/src/web/open.dart.lib.js:644:17
               at Isar.open (http://localhost:58060/packages/isar/src/web/open.dart.lib.js:646:28)
               at http://localhost:58060/packages/givtimer/main.dart.lib.js:216:60
               at Generator.next (<anonymous>)
               at http://localhost:58060/dart_sdk.js:40641:33
               at _rootRunUnary (http://localhost:58060/dart_sdk.js:40937:46)
               at async._CustomZone.new.runUnary (http://localhost:58060/dart_sdk.js:40184:14)
               at _FutureListener.thenAwait.handleValue (http://localhost:58060/dart_sdk.js:35438:29)
               at handleValueCallback (http://localhost:58060/dart_sdk.js:35999:49)
               at _Future._propagateToListeners (http://localhost:58060/dart_sdk.js:36037:17)
               at [_completeWithValue] (http://localhost:58060/dart_sdk.js:35872:23)
               at http://localhost:58060/dart_sdk.js:35906:35
               at _rootRun (http://localhost:58060/dart_sdk.js:40931:14)
               at async._CustomZone.new.run (http://localhost:58060/dart_sdk.js:40178:14)
               at async._AsyncCallbackEntry.new.callback (http://localhost:58060/dart_sdk.js:40128:33)
               at Object._microtaskLoop (http://localhost:58060/dart_sdk.js:40778:13)
               at _startMicrotaskLoop (http://localhost:58060/dart_sdk.js:40784:13)
               at http://localhost:58060/dart_sdk.js:36261:9
```

**Code sample**
```dart
void main() {
  HydratedBlocOverrides.runZoned( () async {
      WidgetsFlutterBinding.ensureInitialized();
      await Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform);

      await Hive.initFlutter();
      DBHelper().activityDb = await Hive.openBox<Map<dynamic, dynamic>>(DBHelper.DB_ACTIVITY_DATA);

      await Isar.open(
        schemas: [ .... ], // assume schema names are here
        directory: kIsWeb ? null : (await getApplicationDocumentsDirectory()).path,
        inspector: true,
      );

      final authenticationRepository = AuthenticationRepository();
      await authenticationRepository.user.first;

      return runApp(App(authenticationRepository: authenticationRepository));
    },
    blocObserver: AppBlocObserver(),
    createStorage: () async {
      WidgetsFlutterBinding.ensureInitialized();
      return HydratedStorage.build(
        storageDirectory: kIsWeb
            ? HydratedStorage.webStorageDirectory
            : await getApplicationDocumentsDirectory(),
      );
    },
  );
}
```

**Version**
 - Platform: Web
 - Flutter version: 3.0.1
 - Isar version: 2.5.0
 - Isar Generator version: 2.5.0

**Attached Files**
[complete-logs.txt](https://github.com/isar/isar/files/8909106/complete-logs.txt)

**Comment by richard457** [comment]
the inspector does not work on the web in isar   2.5.0 try changing to isar: ^3.0.0-dev.1 the inspector is supported on web now.

**Comment by gaganyadav80** [comment]
Hi @richard457, Thank you for your reply. Disabling inspector indeed fixed the error.
