### ISSUE TITLE
Isar Inspector won't connect to iOS simulator throwing WebSocketException

### ISSUE THREAD

**Issue by dimoonchepe** [isar/isar#467]
**Steps to Reproduce**
I've created a minimum app using Isar and run it on iOS simulator (with inspector: true).
When started Isar Inspector (built from the source code) and pasted the link from console (ws://127.0.0.1:50449/oTo1qBsSBAQ=/), I have an exception:

```
flutter: ERROR: Unable to connect to VMService
flutter: WebSocketException: Connection to 'http://127.0.0.1:50449/oTo1qBsSBAQ=/#' was not upgraded to websocket
flutter: #0      _WebSocketImpl.connect (dart:_http/websocket_impl.dart:1011:41)
#1      WebSocket.connect (dart:_http/websocket.dart:360:22)
#2      vmServiceConnectUri (package:vm_service/vm_service_io.dart:32:44)
#3      Service.connect (package:isar_inspector/service.dart:18:29)
#4      _ConnectPageState._connect (package:isar_inspector/connect.dart:24:37)
#5      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:1005:21)
#6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:198:24)
#7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:613:11)
#8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:298:5)
#9      BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:269:7)
#10     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:157:27)
#11     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:449:20)
#12     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:425:22)
#13     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:329:11)
#14     GestureBinding._handlePointerEventImmediately (package:flutter/src/gestures/binding.dart:380:7)
#15     GestureBinding.handlePointerEvent (package:flutter/src/gestures/binding.dart:344:5)
#16     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:302:7)
#17     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:285:7)
#18     _rootRunUnary (dart:async/zone.dart:1442:13)
#19     _CustomZone.runUnary (dart:async/zone.dart:1335:19)
#20     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1244:7)
#21     _invoke1 (dart:ui/hooks.dart:170:10)
#22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:331:7)
#23     _dispatchPointerDataPacket (dart:ui/hooks.dart:94:31)
```

**Version**
 - Platform: iOS
 - Flutter version: 3.0.2
 - Isar version: 2.5.0
 - Isar Generator version: 2.5.0
 - Isar Inspector version: 1.0.0+1

**Comment by leisim** [comment]
Did you test the "old" inspector that runs on your machine or the new one in the browser?

**Comment by dimoonchepe** [comment]
I've tried the one I've discovered [here](https://github.com/isar/isar/releases/tag/2.5.0). 
It says it's new. 
Where can I find the browser one?

**Comment by Anan-Saadi** [comment]
When using the new versions of isar (3.0+) a link will appear in the console
