### ISSUE TITLE
Add support for Linux arm architecture

### ISSUE THREAD

**Issue by guyluz11** [isar/isar#848]
**Is your feature request related to a problem? Please describe.**
My program is running in dart native on a raspberry pi device.

As I am using dart native in order to initialize isar I am using the command `await Isar.initializeIsarCore(download: true);`

But when running my program on my raspberry pi (arm or arm64 architecture) I am getting the following error
short version 
```dart
IsarError: Unsupported processor architecture "linux_arm". Please open an issue on GitHub to request it.
```
Full version

```dart
 Unhandled exception:
2022-10-31T14:25:45+02:00 cbj-hub.cbj-hub[27516]: IsarError: Unsupported processor architecture "linux_arm". Please open an issue on GitHub to request it.
2022-10-31T14:25:45+02:00 cbj-hub.cbj-hub[27516]: #0      _extension#0.localName (package:isar/src/native/isar_core.dart:213)
2022-10-31T14:25:45+02:00 cbj-hub.cbj-hub[27516]: #1      initializeCoreBinary (package:isar/src/native/isar_core.dart:61)
2022-10-31T14:25:45+02:00 cbj-hub.cbj-hub[27516]: #2      Isar.initializeIsarCore (package:isar/src/isar.dart:306)
2022-10-31T14:25:45+02:00 cbj-hub.cbj-hub[27516]: #3      IsarRepository.asyncConstractorHelper (package:cbj_hub/infrastructure/local_db/local_db_repository.dart:65)
2022-10-31T14:25:45+02:00 cbj-hub.cbj-hub[27516]: <asynchronous suspension>
2022-10-31T14:25:45+02:00 cbj-hub.cbj-hub[27516]: #4      IsarRepository.asyncConstractor (package:cbj_hub/infrastructure/local_db/local_db_repository.dart:56)
2022-10-31T14:25:45+02:00 cbj-hub.cbj-hub[27516]: <asynchronous suspension>
2022-10-31T14:25:45+02:00 cbj-hub.cbj-hub[27516]: #5      IsarRepository.getRoomsFromDb (package:cbj_hub/infrastructure/local_db/local_db_repository.dart:124)
2022-10-31T14:25:45+02:00 cbj-hub.cbj-hub[27516]: <asynchronous suspension>
```

And unfortunately this stops me from releasing the next version as I have already made the move to isar and tested it on my main PC (Linux intel x64 architecture). 

**Describe the solution you'd like**
Adding support for arm architecture and making `await Isar.initializeIsarCore(download: true)` download automatically the new version.

**Describe alternatives you've considered**
I have considered moving back to hive local DB, but I think moving to Isar is the correct way for my program so for now I am waiting.

**Version**
 - Platform: Linux
 - Flutter version: dart native
 - Dart version: 2.18.0
 - Isar version: ^3.0.2

**Comment by guyluz11** [comment]
Android is `arm` and `arm64`, does it means that we have the correct files but just didn't include this option with the `download: true`?

**Comment by leisim** [comment]
I didn't manage to get the CI to compile Isar Core for Linux arm.

Also Flutter does not support it anyway I believe.

**Comment by guyluz11** [comment]
Do you suggest to move back to hive or is there something else that I can do to move it forward.

**Comment by guyluz11** [comment]
Where should be my starting point to start compiling isar

**Comment by guyluz11** [comment]
And what error do you get

**Comment by derrikf-spindance** [comment]
I can't get any release builds to run on any Android device I've tested on, I think that this is probably related.

Isar: v3.0.0 and v3.0.2
Devices: Samsung S20, Samsung S10, Google Pixel 4[a]

**Comment by guyluz11** [comment]
> Also Flutter does not support it anyway I believe.

https://github.com/flutter/flutter/issues/114349

**Comment by simc** [comment]
Closing in favour of #876
