### ISSUE TITLE
Add linux_arm64 library

### ISSUE THREAD

**Issue by alkebuware** [isar/isar#876]
**Is your feature request related to a problem? Please describe.**
We're using Dart in the iOT space and are running on a ARM64 Raspberry Pi. A unique use case, but the release package doesn't contain prebuilt binary for download.

**Describe the solution you'd like**
A linux_arm64.so library to added to the binaries in the release package

**Describe alternatives you've considered**
I'm currently downloading the isar source and building the library on the Raspberry Pi.

**Version**
 - Platform: Linux
 - Dart version: 2.18.4
 - Flutter version: N/A
 - Isar version: 3.0.2

**Comment by alkebuware** [comment]
In [build_linux.sh](https://github.com/isar/isar/blob/main/tool/build_linux.sh) we actually build the right library if on a ARM platform. We just need that .so bundled in to to the release.

**Comment by leisim** [comment]
The problem is that there is no way to bundle both a x64 and arm64 library with a Flutter app.

So just not throwing an error is not the way to go

**Comment by alkebuware** [comment]
Correct @leisim. Not throwing an error is not the way to go. Allow me to clarify. My use case involves a Dart command line app that runs as a Daemon on a Raspberry Pi with a Linux ARM 64 CPU architecture. No Flutter involved. isar releases currently don't bundle the library for this architecture. We're not targeting Android with this feature request we're targeting Linux. And build_linux.sh has the necessary steps to build for this platform. I tested out the generated binary, and isar runs like a champ once it's in my path and the change in #877 is applied.

Here's what we'd need to do. 
1. Is there a script that builds the releases? I could not find it. We need to bundle the aarch64-unknown-linux-gnu library with the rest of binaries.
2. Next we need that change I made in #877 since we'd now be building a Linux ARM64 binary. We'd be supporting CPU architecture now that we're compiling it.

Thanks for getting back so quick!

**Comment by leisim** [comment]
The compilation happens in the release workflow in the .github folder. Unfortunately I didn't get the arm compilation to work on the x64 github runnner 😕

**Comment by alkebuware** [comment]
@simc understood. I don't have much experience with github's CICD environment, but have you considered using docker to spin up an ARM64 docker image and running the linux ARM build in that. Can you point me in the direction to the CICD configs? In the repo. If possible I'd like to take a try and opening a pull request for it.

**Comment by vleeuwenmenno** [comment]
I am trying to build on M1 Pro and I run dockerized so I need the arm64 versions. Any update on this? Did anyone manage to get a working arm64 version?

**Comment by videah** [comment]
I've successfully built arm64 Isar in an x64 github runner for my project, [albeit in a Docker image and it was very slow](https://github.com/videah/SkyBridge/actions/runs/5034285777/jobs/9029012951).

I was initially having issues with the runner getting killed with an out of memory error code. Maybe this was the issue you encountered @simc? I fixed it by setting the environment variable `CARGO_NET_GIT_FETCH_WITH_CLI` to true.

**Comment by simc** [comment]
I'm able to build an arm64 linux binary now. Does anyone know how to bundle x64 and arm64 binaries in the Flutter `CMakeLists.txt`?

**Comment by sauramirez** [comment]
Maybe by adding the target @simc ?

```
set(isar_flutter_libs_bundled_libraries
  "$<TARGET_FILE:libisar>"
  PARENT_SCOPE
)
```

Taken from https://medium.com/flutter-community/build-and-deploy-native-c-libraries-with-flutter-cc7531d590b5

**Comment by guyluz11** [comment]
Related to #848

**Comment by BigGitWorld** [comment]
> I'm able to build an arm64 linux binary now. Does anyone know how to bundle x64 and arm64 binaries in the Flutter `CMakeLists.txt`?

Does the isar supports arm64 (Raspberry-pi) now?

**Comment by guyluz11** [comment]
Guy's please also upvote the issue, it makes it easier to see how many people effected by that.

**Comment by pieter-scholtz** [comment]
@simc How are you building the binary ? I attempted to build it on my linux desktop using `cargo build --target aarch64-unknown-linux-gnu --release` But I am getting some errors : 

```
warning: unused import: `xxhash_rust::xxh3::xxh3_64_with_seed`
  --> packages/isar_core/src/schema/mod.rs:12:5
   |
12 | use xxhash_rust::xxh3::xxh3_64_with_seed;
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: `#[warn(unused_imports)]` on by default

warning: using `.deref()` on a double reference, which returns `&&[u8]` instead of dereferencing the inner type
  --> packages/isar_core/src/collection.rs:81:25
   |
81 |             let id = key.deref().to_id();
   |                         ^^^^^^^^
   |
   = note: `#[warn(suspicious_double_ref_op)]` on by default

warning: using `.deref()` on a double reference, which returns `&&[u8]` instead of dereferencing the inner type
  --> packages/isar_core/src/link.rs:65:34
   |
65 | ...   callback(id_bytes.deref().to_id(), IsarObject::from_bytes(&object))
   |                        ^^^^^^^^

warning: `isar-core` (lib) generated 3 warnings (run `cargo fix --lib -p isar-core` to apply 1 suggestion)
error: linking with `cc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/pieter-scholtz/snap/rustup/common/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/pieter-scholtz/.cargo/bin:/home/pieter-scholtz/.local/bin:/home/pieter-scholtz/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/snap/bin:/home/pieter-scholtz/Chromium/depot_tools:/home/pieter-scholtz/KDAB/flutter/bin" VSLANG="1033" "cc" "-Wl,--version-script=/tmp/rustcx2P0kB/list" "-Wl,--no-undefined-version" "/tmp/rustcx2P0kB/symbols.o" "/home/pieter-scholtz/Downloads/isar-3.1.0-1/target/aarch64-unknown-linux-gnu/release/deps/isar.isar.e33a8ec2e1683f78-cgu.0.rcgu.o" "-Wl,--as-needed" "-L" "/home/pieter-scholtz/Downloads/isar-3.1.0-1/target/aarch64-unknown-linux-gnu/release/deps" "-L" "/home/pieter-scholtz/Downloads/isar-3.1.0-1/target/release/deps" "-L" "/home/pieter-scholtz/Downloads/isar-3.1.0-1/target/aarch64-unknown-linux-gnu/release/build/mdbx-sys-d9bed4ca25b1c2fc/out" "-L" "/home/pieter-scholtz/snap/rustup/common/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/rustcx2P0kB/libmdbx_sys-1b27e98f7261b200.rlib" "/home/pieter-scholtz/snap/rustup/common/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libcompiler_builtins-21239b3d9ec3b48b.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/pieter-scholtz/snap/rustup/common/rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib" "-o" "/home/pieter-scholtz/Downloads/isar-3.1.0-1/target/aarch64-unknown-linux-gnu/release/deps/libisar.so" "-Wl,--gc-sections" "-shared" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-Wl,--strip-all" "-nodefaultlibs"
  = note: /usr/bin/ld: /home/pieter-scholtz/Downloads/isar-3.1.0-1/target/aarch64-unknown-linux-gnu/release/deps/isar.isar.e33a8ec2e1683f78-cgu.0.rcgu.o: Relocations in generic ELF (EM: 183)

```
My rust knowledge is basically nonexistent , so not quite sure what this means.

**Comment by pieter-scholtz** [comment]
So It works if I build it like this : `RUSTFLAGS="-C linker=aarch64-linux-gnu-gcc" cargo build --target aarch64-unknown-linux-gnu --release` on ubuntu 22.04 with the toolchain installed using the package manager.

**Comment by guyluz11** [comment]
Adding the link to some dart feature that is in progress, maybe it will simplify some of the process in initializing this package and give a tool to more easily solve this one
https://github.com/dart-lang/sdk/issues/50565

**Comment by SebAubin** [comment]
Is there any development on this? We use Isar and we're trying to add support for Linux Arm64 for our app.

**Comment by CaptainDario** [comment]
I am trying to get my app running on linux arm64.
@simc do you have plans on supporting this?

**Comment by onny** [comment]
@FritzMatthaeus 
> I forked isar version 3.1.0 (as my code does not implement isar 4 yet) and made the following changes:
> 
>     1. I added the code as @sauramirez mentioned in CMakeLists.txt
> 
> 
> [#876 (comment)](https://github.com/isar/isar/issues/876#issuecomment-1562105766)

I replaced the part in the `CMakeLists.txt` file but now I get 

```
Building Linux application...                                   
CMake Error:
  Error evaluating generator expression:

    $<TARGET_FILE:libisar>

  No target "libisar"


CMake Generate step failed.  Build files cannot be regenerated correctly.
Unable to generate build files
```

how did you add the `add_subdirectory` part?

**Comment by FritzMatthaeus** [comment]
> @FritzMatthaeus
> 
> > I forked isar version 3.1.0 (as my code does not implement isar 4 yet) and made the following changes:
> > ```
> > 1. I added the code as @sauramirez mentioned in CMakeLists.txt
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [#876 (comment)](https://github.com/isar/isar/issues/876#issuecomment-1562105766)
> 
> I replaced the part in the `CMakeLists.txt` file but now I get
> 
> ```
> Building Linux application...                                   
> CMake Error:
>   Error evaluating generator expression:
> 
>     $<TARGET_FILE:libisar>
> 
>   No target "libisar"
> 
> 
> CMake Generate step failed.  Build files cannot be regenerated correctly.
> Unable to generate build files
> ```
> 
> how did you add the `add_subdirectory` part?

I am sorry, but i can't help you on this. I did the steps i've mentioned and didn't try to dig deeper in understanding the code. That's already a couple of months back and i did not work on this anymore since. I currently have no access to the development machine i forked the code on, so i can't look it up. Sorry :/

**Comment by onny** [comment]
without the modification to `isar/packages/isar_flutter_libs/linux/CMakeLists.txt` I get
```
Building Linux application...                                   
CMake Error at cmake_install.cmake:124 (file):
  file INSTALL cannot find
  "/root/finamp/linux/flutter/ephemeral/.plugin_symlinks/isar_flutter_libs/linux/libisar.so":
  No such file or directory.


Build process failed
```

**Comment by Frederik-VP** [comment]
We were surprised to see this. easily fixable it seems from the comments, but not very nice to hardcode for a given architecture in your build system. 

Sad that the support for the project is not present :(

**Comment by athvaith8282** [comment]
> > I'm able to build an arm64 linux binary now. Does anyone know how to bundle x64 and arm64 binaries in the Flutter `CMakeLists.txt`?
> 
> Does the isar supports arm64 (Raspberry-pi) now? I'm getting the below error when use the isar (version 3.1.0+1) in a **flutter-pi** project.
> 
> ```
> [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: IsarError: Unsupported processor architecture "linux_arm64". Please open an issue on GitHub to request it.
> #0      _extension#1.localName (package:isar/src/native/isar_core.dart:213)
> #1      initializeCoreBinary (package:isar/src/native/isar_core.dart:61)
> #2      openIsar (package:isar/src/native/open.dart:81)
> #3      Isar.open (package:isar/src/isar.dart:107)
> #4      initIsarDB (package:test/main.dart:59)
> <asynchronous suspension>
> ```

Did you able to resolve this error ?
I am also  facing the same error

**Comment by athvaith8282** [comment]
> Maybe by adding the target @simc ?
> 
> ```
> set(isar_flutter_libs_bundled_libraries
>   "$<TARGET_FILE:libisar>"
>   PARENT_SCOPE
> )
> ```
> 
> Taken from https://medium.com/flutter-community/build-and-deploy-native-c-libraries-with-flutter-cc7531d590b5

In which file, i needs to add this changes ?

and what is the steps to build and use isar for raspberrypi (linux_arm64) ?
