### ISSUE TITLE
IllegalArg: Object is bigger than 16MB when object is much smaller

### ISSUE THREAD

**Issue by mdrideout** [isar/isar#912]
### Steps to Reproduce

Testing storage of an image converted to `List<int>` of 7MB (7,302,242 bytes), and receiving error `Object is bigger than 16MB` exception.

Use case: cross-platform image caching

```bash
flutter: Uint8List size: 7302242
flutter: List<int> size: 7302242
[VERBOSE-2:dart_vm_initializer.cc(41)] Unhandled Exception: IsarError: IllegalArg: Object is bigger than 16MB.
```

### Code sample

```dart
@collection
class CachedData {
  CachedData(this.storageRefFullPath, this.bytes, this.cacheCreated, this.cacheExpires);

  /// The full path of the [Reference] storage ref (because the [Reference] object is not compatible with isar)
  final String storageRefFullPath;

  /// The Isar Item ID
  Id get id => stringToHash(storageRefFullPath);

  /// The bytes stored
  final List<int> bytes;

  /// Cache created
  final DateTime cacheCreated;

  /// Cache expires
  final DateTime cacheExpires;

  /// Cache Now
  /// Caches an already downloaded Firebase Storage reference
  /// and its bytes for future use.
  static Future<void> cacheBytes({
    required Reference storageRef,
    required Uint8List bytes,
    Duration cacheDuration = const Duration(minutes: 5),
  }) async {
    // Create cacheCreated datetime
    DateTime now = DateTime.now();

    // Create an expiration from the duration
    DateTime expires = now.add(cacheDuration);

    // Construct the entire cache object
    CachedData cachedData = CachedData(storageRef.fullPath, bytes, now, expires);

    final Isar? isar = Isar.getInstance(FireproofCloset.kDatabaseName);
    if (isar == null) {
      throw ("Unable to get Isar instance: ${FireproofCloset.kDatabaseName}");
    }

    try {
      await isar.writeTxn(() async {
        int id = await isar.cachedDatas.put(cachedData);
        debugPrint("cacheBytes() saved to Isar. id: $id");
      });
    } catch (e) {
      debugPrint(
          "cacheBytes() failed to write to Isar database.\nPath: ${storageRef.fullPath},\nUint8List size: ${bytes.lengthInBytes}\nList<int> size: ${bytes.toList().length}");
      rethrow;
    }

    return;
  }
}
```

**General Question**: Is there a reason this is limited to 16MB?

### Details

 - Platform: iOS Emulator 16.1 iPad Air 5th Generation
 - Flutter version: Flutter 3.3.8
 - Isar version:
   - isar: ^3.0.5
   - isar_flutter_libs: ^3.0.5
   - isar_generator: ^3.0.5
  
---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by mdrideout** [comment]
Additional note: I've been expirementing with various image sizes to see what the real max is. 

Saving a 2,289,802 bytes image, the save appeared to work. But attempts to read the data caused it to have the following exception:
```bash
======== Exception caught by image resource service ================================================
The following FormatException was thrown resolving an image codec:
Unexpected extension byte (at offset 1541235)

When the exception was thrown, this was the stack: 
#0      _Utf8Decoder.convertSingle (dart:convert-patch/convert_patch.dart:1755:7)
#1      Utf8Decoder.convert (dart:convert/utf.dart:351:42)
#2      IsarReaderImpl.readStringOrNull (package:isar/src/native/isar_reader_impl.dart:242:24)
#3      IsarReaderImpl.readString (package:isar/src/native/isar_reader_impl.dart:224:12)
#4      _cachedDataDeserialize (package:fireproof_closet/src/cached_data.g.dart:85:12)
#5      IsarCollectionImpl.deserializeObject (package:isar/src/native/isar_collection_impl.dart:42:38)
#6      IsarCollectionImpl.deserializeObjectsOrNull (package:isar/src/native/isar_collection_impl.dart:78:22)
#7      IsarCollectionImpl.getAll.<anonymous closure> (package:isar/src/native/isar_collection_impl.dart:168:14)
<asynchronous suspension>
#8      IsarCommon._beginTxn (package:isar/src/common/isar_common.dart:54:18)
<asynchronous suspension>
#9      CachedData.getFromCache (package:fireproof_closet/src/cached_data.dart:42:38)
<asynchronous suspension>
#10     FireproofImage._loadAsync (package:fireproof_closet/src/fireproof_image_provider.dart:93:38)
<asynchronous suspension>
Image provider: FireproofImage("Reference(app: [DEFAULT], fullPath: user-uploads/ooWqOgaDwktSgZP6N0Pr/author-image/two-two.jpg)", scale: 1.0)
Image key: FireproofImage("Reference(app: [DEFAULT], fullPath: user-uploads/ooWqOgaDwktSgZP6N0Pr/author-image/two-two.jpg)", scale: 1.0)
====================================================================================================
```

Loading the Isar debug browser caused the app. to crash in simulator. However, interestingly, in the debug browser (before crash) it displays the **2,289,802 bytes image** as being **17.48 MB**.

<img width="350" alt="inspector" src="https://user-images.githubusercontent.com/3958274/202875778-5b358813-e0a7-4c6d-b36b-104d52021ec1.png">

**Comment by leisim** [comment]
Change `final List<int> bytes;` to `final List<byte> bytes;`

**Comment by mdrideout** [comment]
Thank you for the fast response.

I can confirm that changing it to `final List<byte> bytes;` worked and solved the size discrepancy issue as well.

The data I provided to this was type `Uint8List`. Is it possible for the [schema](https://isar.dev/schema.html#supported-types) to support this type since many dart image and file handing functions use this? Otherwise, it would be good in the docs to know that `List<byte>` is an option and that it's compatible.

**Comment by leisim** [comment]
Uint8List is a List<byte> so the two types are compatible. I'll add some more information to the docs 🙂
