### ISSUE TITLE
Unit test fails "nhandled error during finalization of test"

### ISSUE THREAD

**Issue by dewbambs** [isar/isar#947]
### Steps to Reproduce

I migrated from isar 3.0.0-dev.0 to 3.0.5. There were a lot of breaking changes which I fixed. When I tried running my unit test which worked perfectly before. I got the following error.

```
nhandled error during finalization of test:
/Users/riteshsingh/Documents/Projects/CidroyProjects/yatrikart-hawker-app/packages/yatrikart_data_layer/test/src/cart/cart_local_test.dart
TestDeviceException(Shell subprocess crashed with segmentation fault.)
#0      FlutterTesterTestDevice.finished (package:flutter_tools/src/test/flutter_tester_device.dart:241:5)
<asynchronous suspension>
#1      FlutterTesterTestDevice.kill (package:flutter_tools/src/test/flutter_tester_device.dart:223:5)
<asynchronous suspension>
#2      FlutterPlatform._startTest.<anonymous closure> (package:flutter_tools/src/test/flutter_platform.dart:485:9)
<asynchronous suspension>
#3      FlutterPlatform._startTest (package:flutter_tools/src/test/flutter_platform.dart:538:11)
<asynchronous suspension>
```

Command used to run test

`flutter test -j 1`

### Code sample

This is my isar initialisation code for the unit test.

```dart
setUpAll(() async {
    await Isar.initializeIsarCore(download: true);
    final dartToolDir = path.join(Directory.current.path, '.dart_tool');
    testTempPath = path.join(dartToolDir, 'test', 'tmp');
    isar = await Isar.open(
      [OfferSchema, SyncSchema, CheckoutSchema, ProductSchema],
      directory: testTempPath,
    );
  });
```

### Reproduce error

dummy_test.dart
```dart

class FakePathProviderPlatform extends Fake
    with MockPlatformInterfaceMixin
    implements PathProviderPlatform {
  @override
  Future<String?> getApplicationSupportPath() async {
    final dartToolDir = path.join(Directory.current.path, '.dart_tool');
    final testTempPath = path.join(dartToolDir, 'test', 'tmp');
    return testTempPath;
  }
}

void main() {
  setUpAll(() async {
    PathProviderPlatform.instance = FakePathProviderPlatform();
    await Isar.initializeIsarCore(download: true);
  });

  test('should be singleton', () async {
    final DatabaseInitialisation hiveInitialisation = DatabaseInitialisation();
    await hiveInitialisation.dbInit();
    expect(
      DatabaseInitialisation.instance.isar,
      DatabaseInitialisation.instance.isar,
    );
  });
}
```

dummy.dart
```dart

/// Hive initialisation class will be used for initialising the hive box.
/// All the instance of hive in data layer will be given from this class.
class DatabaseInitialisation {
  /// Making DBInitialization class singleton
  factory DatabaseInitialisation() => _hiveInitialisation;

  DatabaseInitialisation._();

  static final DatabaseInitialisation _hiveInitialisation =
      DatabaseInitialisation._();

  /// instance of Hive box
  static DatabaseInitialisation get instance {
    // will throw LateInitializationError if not initialized
    // is a anti-patern to use late for public variable but to avoid major
    // changes in the code we are using late
    // _hiveInitialisation.isar;
    return _hiveInitialisation;
  }

  /// this Isar instance will be used through out the project for isar instance
  late Isar isar;

  /// The Hive Init method will initialize hive box.
  Future<void> dbInit() async {
    try {
      final dir = await getApplicationSupportDirectory();
      log(dir.path);

      isar = await Isar.open(
        [OfferSchema, SyncSchema, CheckoutSchema, ProductSchema],
        directory: dir.path,
      );
    } catch (error) {
      rethrow;
    }
  }
}

```

### Details

 - Flutter version: 3.3.9
 - Isar version: 3.0.5

---

 - [x] I searched for similar issues already
 - [x] I filled the details section with the exact device model and version
 - [x] I am able to provide a reproducible example

**Comment by fayaz-modz** [comment]
did you figure it out?

**Comment by dewbambs** [comment]
no

**Comment by simc** [comment]
This should be fixed with v4
